application:
  subdomain: t3mt
  upstreams:
    - location: /
      backend: http://t3mt-service:80/
  public_path:
    - /

services:
  t3mt-service:
    # upstream: 85423296/t3mt:2.1.5
    image: docker.1ms.run/85423296/t3mt:2.1.5
    environment:
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/data:/app/backend/data
      - /lzcapp/var/logs:/app/backend/logs
      - /lzcapp/var/downloads:/app/backend/downloads
    cpu_shares: 512
    mem_limit: 512M
