name: T3MT
package: community.lazycat.app.t3mt
version: 2.1.5
min_os_version: 1.3.8
description: "Free media management assistant with automatic download support for Quark, Tencent, iQiyi, Mango TV, Youku and more"
license: MIT
homepage: https://github.com/qq85423296/t3mt
author: qq85423296

application:
  subdomain: t3mt
  upstreams:
    - location: /
      backend: http://t3mt-service:80/
  public_path:
    - /

services:
  t3mt-service:
    # 85423296/t3mt:2.1.5
    image: registry.lazycat.cloud/czyt/85423296/t3mt:cb33edb939b5f1b7
    environment:
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/data:/app/backend/data
      - /lzcapp/var/logs:/app/backend/logs
      - /lzcapp/var/downloads:/app/backend/downloads
    cpu_shares: 512
    mem_limit: 512M

locales:
  en:
    name: "T3MT"
    description: "Free media management assistant with automatic download support for Quark, Tencent, iQiyi, Mango TV, Youku and more"
  zh:
    name: "T3MT"
    description: "免费影视管理助手，夸克全自动下载，腾讯、爱奇艺、芒果、优酷等影视资源全自动更新下载"

unsupported_platforms:
  - ios
  - android
  - tvos
